### ISSUE TITLE
Illuminance Startup Error (Darksky)

### ISSUE THREAD

**Issue by mattrayner** [pnbruckner/ha-illuminance#33]
Hi,
 I've updated to the latest version of the integration through HACS and am seeing this error:

```
Logger: homeassistant.setup
Source: setup.py:334 
First occurred: 10:58:27 (1 occurrences) 
Last logged: 10:58:27

Unable to prepare setup for platform illuminance.sensor: (DependencyError(...), 'Could not setup dependencies: darksky')
```

I don't have dark sky setup, and I guess I can't because the APIs are now depreciated, so not sure how to fix this

**Comment by mattrayner** [comment]
No worries, I've rolled back to 3.1 :)

Thanks for all your work on this, if there's anything I can do to help, let me know 👍

**Comment by pnbruckner** [comment]
3.2.0 should work for you, too. Have you tried it?

FWIW, I've deleted the 3.2.1 release and will shortly replace it with a 3.2.2 that resolves this issue.

The problem was I added some automatic tests HACS recommends, once of which is HA's "hassfest", and it complained about not having darksky as a dependency because the illuminance code has one import from the darksky component _in case_ the config uses a darksky entity. Listing it as a dependency, however, causes HA to attempt to load it, and loading it requires a valid config for it. Of course, when I tested, I _did_ have a valid darksky config, so I missed this issue.
