### ISSUE TITLE
Documentation is unclear

### ISSUE THREAD

**Issue by itsmartinho** [pnbruckner/ha-illuminance#37]
Hello, 

I've installed the integration with HACS.
Then added:

`# Illuminance
  - platform: illuminance
    entity_id: weather.accuweather_house`

and

`  - sensor:
      - name: "LUX: Exterior"
        unique_id: lux_exterior
        state: "{{ state_attr('weather.accuweather_house', 'illuminance') }}"`

but those just don't work. I can't seem to make this sensor work.
I'm using accuweather. being the entiry "weather.accuweather_house"

**Comment by itsmartinho** [comment]
Managed to fix this - no idea how actually but the sensor started updating. 
Don't waste your time trying to help. Appreciate your time!

**Comment by itsmartinho** [comment]
Thank you for the explanation, that's precisely my mistake lol.
I was checking for a `_illuminance` state of Accuweather. Meanwhile I was probably scrolling over that `illuminance` over and over. 

Might be a good idea to update your Github with that, or a note or something. I can see a lot of people accidentally overcomplicating it when it's just so simple :D

**Comment by pnbruckner** [comment]
> Might be a good idea to update your Github with that, or a note or something. I can see a lot of people accidentally overcomplicating it when it's just so simple :D

Well, simply via the configuration entry, it should be pretty obvious that you are creating a new `sensor` entity. It goes under `sensor` after all. 😉 

But, yeah, I guess users are getting more and more used to doing things via the UI, and when they have to do something in YAML, it gets them confused. (I've been using HA since before the UI configuration infrastructure was useable, so I think YAML first. lol)

I can add a note to README.md & info.md to hopefully make it clearer.

**Comment by pnbruckner** [comment]
@itsmartinho, check out the prosed changes in the linked PR and let me know if you think they will help. Thanks!
