### ISSUE TITLE
Darksky in manifest ?

### ISSUE THREAD

**Issue by titiviking** [pnbruckner/ha-illuminance#44]
Hi,

I've just downloaded the updated version of this without the DarkSky dependency.
I do still see the DarkSky reference in the manifest. Is this something that can be equally removed, or does it still server a purpose ?

**Comment by pnbruckner** [comment]
It does in case anyone is still using this with an older version of HA. But, if the DarkSky API has completely shut down, then yes, I can remove this. I just haven't verified myself yet.

**Comment by rlad78** [comment]
There are actually a good many people who use [Pirate Weather](https://github.com/alexander0042/pirate-weather-ha), which aims to be a drop in replacement for Dark Sky in HA. Might be worthwhile to adjust for that instead.

**Comment by pnbruckner** [comment]
Hopefully, shouldn't be necessary. A recent release made this integration more "generic." I.e., it doesn't necessarily need to know anything about the weather entity. If the weather entity's state is numeric, it will assume it's a could percentage. If not, it will assume its a weather condition and meets the generic list of conditions. There is currently only special mappings (i.e., condition to illuminance factor) for accuweather & ecobee. All others seem to work with the generic mapping.

I'm in the process of removing the last remnants of darksky support, since clearly its API has shut down, and not even people using older versions of HA can use darksky.
