### ISSUE TITLE
FR: Add irradiance equivalent as an output option

### ISSUE THREAD

**Issue by wigster** [pnbruckner/ha-illuminance#63]
Rather than for light levels, I am using the irradiance sensors to estimate how much heat my windows are getting from the Sun and whether it is worth it to close the blinds.

The conversion factor from lx to W/m2 for the Sun is around 120 lx/(W/m2), so it's just a constant value for the relevant range of Solar illuminances. Here is a reference:

https://www.extrica.com/article/21667

Could you add irradiance as an output option to your integration?

**Comment by pnbruckner** [comment]
I just released 5.5.0b0 that makes the input weather entity optional. Assuming that goes well, I'll release it as 5.5.0, and then I'll start working on this feature.

**Comment by pnbruckner** [comment]
@wigster, actually, I'm going to include the irradiance sensor in a 5.5.0b1 beta release. I have it working already. After testing for a day, I'll release the beta. FWIW, the way I implemented it is by adding a third "mode" option. In addition to normal & simple, I added irradiance, which behaves like normal, but the value is converted from lux to Watts/m² using the conversion factor described in that article. Let me know if you're willing to test this. Thanks!

**Comment by pnbruckner** [comment]
Released 5.5.0b1 with new irradiance mode option.

**Comment by wigster** [comment]
Hi -- I've just checked this out -- it appears pretty close to my local weather station's output, so great. Thanks for doing this!

One comment would be that the sensor to have spurious precision -- multiple significant figures and decimal places. Given the fact that cloud cover only get reported with +-10% precision by the weather services and who knows how accurate that is in any real location, it seems like having more than a couple of significant figures is spurious. Maybe it makes sense to just round to an integer, not least to reduce the data in the recorder?

**Comment by pnbruckner** [comment]
The calculation of illuminance, and hence irradiance, is based on mathematical models. Honestly, I can't recall if the article where I got the models from made any statements about precision. And, for that matter, those calculations are based on other models that are used to calculate the sun's elevation (i.e., from the astral package.)

Bottom line, I didn't worry about significant digits. I've always just pretty much rounded illuminance to an integer. Since irradiance is two orders of magnitude smaller, I decided to give it at least one decimal place of precision (although, I suppose, I should have set it to two to be "equivalent.")

The user can always override the precision.
